import { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from './types';

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    appName: 'Digital Agronomist',
    welcome: 'Welcome,',
    manageCrops: 'Manage your crops correctly.',
    login: 'Login to Account',
    loginDesc: 'Provide information to enter your farm.',
    phoneOrEmail: 'Phone or Email',
    password: 'Password',
    forgotPassword: 'Forgot?',
    loginBtn: 'Login to Dashboard',
    orContinue: 'Or continue with',
    google: 'Google',
    otp: 'OTP',
    noAccount: "Don't have an account?",
    signupFree: 'Sign up for free',
    getStarted: 'Get Started',
    smartFarmer: 'Smart Farmer',
    aiDriven: 'AI Driven Farming',
    accuracy: 'Accuracy',
    advisor: 'Advisor',
    home: 'Home',
    fields: 'Fields',
    aiTools: 'AI Tools',
    profile: 'Profile',
    myFields: 'My Fields',
    seeAll: 'See All',
    expertTools: 'Expert Tools',
    cropSelection: 'Crop Selection',
    diseaseDetection: 'Disease Detection',
    fieldMapping: 'Field Mapping',
    farmingTips: 'Farming Tips',
    weeklyFocus: 'Weekly Focus',
    waterUsage: 'Best Water Usage in Drought',
    readGuide: 'Read Guide',
    soilHealth: 'Soil Health Diagnosis',
    weatherImpact: 'Weather Impact',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    phLevel: 'pH Level',
    ideal: 'Ideal',
    medium: 'Medium',
    high: 'High',
    acidic: 'Acidic',
    scanCrops: 'Scan your crops for problems',
    scanDesc: 'Our AI analyzes leaf patterns to instantly identify diseases and provide expert-approved remedies.',
    uploadCapture: 'Upload or Capture Crop Image',
    uploadDesc: 'Take a clear picture of the affected leaf. Ensure sufficient natural light for best results.',
    openCamera: 'Open Camera',
    selectGallery: 'Select from Gallery',
    expertAdvice: 'Expert Advice',
    waitingImage: 'Waiting for image...',
    identified: 'Identified',
    riceBlast: 'Rice Blast Fungus',
    recommendedActions: 'Recommended Actions',
    irrigationControl: 'Irrigation Control',
    fungicideApp: 'Fungicide Application',
    buyRemedy: 'Buy Remedy',
    fieldMapper: 'Field Mapper',
    myLand: 'My Land',
    manageLand: 'Manage your agricultural land perfectly.',
    activeFields: 'Active Fields',
    avgMoisture: 'Avg. Moisture Level',
    savedPlots: 'Saved Plots',
    area: 'Area',
    soilType: 'Soil Type',
    growth: 'Growth',
    signup: 'Create New Account',
    signupDesc: 'Start your smart farming journey.',
    name: 'Name',
    phone: 'Phone Number',
    district: 'District',
    selectDistrict: 'Select your district',
    agreeTerms: 'I agree to the terms.',
    createAccount: 'Create Account',
    alreadyAccount: 'Already have an account?',
    knowledgeCenter: 'Knowledge Center',
    expertConsultation: 'Expert Advice',
    seasonalInsights: 'Seasonal Insights',
    allMethods: 'All Methods',
    cropTips: 'Crop Tips',
    seasonal: 'Seasonal',
    pestAlert: 'Pest Alert',
    leafhopper: 'Leafhopper Detection',
    tomatoCare: 'Crop Tips: Tomato Care',
    toolCare: 'Best Practice: Tool Care',
    smartIrrigation: 'Smart Irrigation System',
    moreAdvice: 'See More Advice',
    pageOf: 'Page {current} of {total}',
    logout: 'Logout from Account'
  },
  bn: {
    appName: 'ডিজিটাল কৃষিবিদ',
    welcome: 'স্বাগতম,',
    manageCrops: 'সঠিকভাবে আপনার ফসল পরিচালনা করুন।',
    login: 'অ্যাকাউন্টে লগইন করুন',
    loginDesc: 'আপনার খামারে প্রবেশ করতে তথ্য প্রদান করুন।',
    phoneOrEmail: 'ফোন বা ইমেইল',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'ভুলে গেছেন?',
    loginBtn: 'ড্যাশবোর্ডে লগইন করুন',
    orContinue: 'অথবা চালিয়ে যান',
    google: 'গুগল',
    otp: 'ওটিপি',
    noAccount: 'অ্যাকাউন্ট নেই?',
    signupFree: 'বিনামূল্যে সাইন আপ করুন',
    getStarted: 'শুরু করুন',
    smartFarmer: 'স্মার্ট কৃষক',
    aiDriven: 'এআই এর সাথে বুদ্ধিমান চাষ',
    accuracy: 'নির্ভুলতা',
    advisor: 'পরামর্শদাতা',
    home: 'হোম',
    fields: 'জমি',
    aiTools: 'এআই টুলস',
    profile: 'প্রোফাইল',
    myFields: 'আমার জমিসমূহ',
    seeAll: 'সব দেখুন',
    expertTools: 'বিশেষজ্ঞ সরঞ্জাম',
    cropSelection: 'ফসল নির্বাচন',
    diseaseDetection: 'রোগ শনাক্তকরণ',
    fieldMapping: 'মাঠ মানচিত্র',
    farmingTips: 'চাষাবাদ টিপস',
    weeklyFocus: 'সাপ্তাহিক গুরুত্ব',
    waterUsage: 'খরার সময় পানির সর্বোত্তম ব্যবহার',
    readGuide: 'গাইডটি পড়ুন',
    soilHealth: 'মাটির স্বাস্থ্যের রোগনির্ণয়',
    weatherImpact: 'আবহাওয়ার প্রভাব',
    nitrogen: 'নাইট্রোজেন (N)',
    phosphorus: 'ফসফরাস (P)',
    potassium: 'পটাশিয়াম (K)',
    phLevel: 'pH মাত্রা',
    ideal: 'আদর্শ',
    medium: 'মাঝারি',
    high: 'উচ্চ',
    acidic: 'অম্লীয়',
    scanCrops: 'সমস্যার জন্য আপনার ফসল স্ক্যান করুন',
    scanDesc: 'আমাদের AI পাতার প্যাটার্ন বিশ্লেষণ করে তাৎক্ষণিকভাবে রোগ শনাক্ত করে এবং বিশেষজ্ঞ-অনুমোদিত প্রতিকার প্রদান করে।',
    uploadCapture: 'ফসলের ছবি আপলোড বা ক্যাপচার করুন',
    uploadDesc: 'আক্রান্ত পাতার একটি পরিষ্কার ছবি নিন। ভালো ফলাফলের জন্য পর্যাপ্ত প্রাকৃতিক আলো নিশ্চিত করুন।',
    openCamera: 'ক্যামেরা খুলুন',
    selectGallery: 'গ্যালারি থেকে নির্বাচন করুন',
    expertAdvice: 'বিশেষজ্ঞ পরামর্শ',
    waitingImage: 'ছবির জন্য অপেক্ষা করছে...',
    identified: 'শনাক্তকৃত',
    riceBlast: 'ধানের ব্লাস্ট ছত্রাক',
    recommendedActions: 'প্রস্তাবিত পদক্ষেপসমূহ',
    irrigationControl: 'সেচ নিয়ন্ত্রণ',
    fungicideApp: 'ছত্রাকনাশক প্রয়োগ',
    buyRemedy: 'প্রতিকার কিনুন',
    fieldMapper: 'ফিল্ড ম্যাপার',
    myLand: 'আমার জমি',
    manageLand: 'আপনার কৃষি জমি নিখুঁতভাবে পরিচালনা করুন।',
    activeFields: 'সক্রিয় জমি',
    avgMoisture: 'গড় আর্দ্রতা লেভেল',
    savedPlots: 'সংরক্ষিত জমি',
    area: 'জমির আকার',
    soilType: 'মাটির ধরন',
    growth: 'বৃদ্ধি',
    signup: 'নতুন অ্যাকাউন্ট তৈরি করুন',
    signupDesc: 'স্মার্ট চাষের যাত্রা শুরু করুন।',
    name: 'নাম',
    phone: 'ফোন নম্বর',
    district: 'জেলা',
    selectDistrict: 'আপনার জেলা নির্বাচন করুন',
    agreeTerms: 'আমি শর্তাবলীর সাথে একমত।',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    alreadyAccount: 'আগে থেকেই অ্যাকাউন্ট আছে?',
    knowledgeCenter: 'তথ্য কেন্দ্র',
    expertConsultation: 'বিশেষজ্ঞ পরামর্শ',
    seasonalInsights: 'মৌসুমি ধারণা।',
    allMethods: 'সব পদ্ধতি',
    cropTips: 'ফসল টিপস',
    seasonal: 'মৌসুমি',
    pestAlert: 'পোকামাকড় সতর্কবার্তা',
    leafhopper: 'লিফহপার শনাক্তকরণ',
    tomatoCare: 'ফসল টিপস: টমেটোর যত্ন',
    toolCare: 'সেরা পদ্ধতি: সরঞ্জামের যত্ন',
    smartIrrigation: 'স্মার্ট সেচ ব্যবস্থা',
    moreAdvice: 'আরও পরামর্শ দেখুন',
    pageOf: 'পৃষ্ঠা {current} এর {total}',
    logout: 'অ্যাকাউন্ট থেকে লগ আউট করুন'
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('bn');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <AppContext.Provider value={{ language, setLanguage, t }}>
      <div lang={language}>
        {children}
      </div>
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) throw new Error('useApp must be used within AppProvider');
  return context;
}
