import { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { Language } from './types';
import { useAuth } from './AuthContext';
import { doc, onSnapshot } from 'firebase/firestore';
import { db } from './lib/firebase';

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    appName: 'Digital Agronomist',
    welcome: 'Welcome,',
    manageCrops: 'Manage your crops correctly.',
    login: 'Login to Account',
    loginDesc: 'Provide information to enter your farm.',
    phoneOrEmail: 'Phone or Email',
    password: 'Password',
    forgotPassword: 'Forgot?',
    loginBtn: 'Login to Dashboard',
    orContinue: 'Or continue with',
    google: 'Google',
    otp: 'OTP',
    noAccount: "Don't have an account?",
    signupFree: 'Sign up for free',
    getStarted: 'Get Started',
    smartFarmer: 'Smart Farmer',
    aiDriven: 'AI Driven Farming',
    accuracy: 'Accuracy',
    advisor: 'Advisor',
    home: 'Home',
    fields: 'Fields',
    aiTools: 'AI Tools',
    profile: 'Profile',
    myFields: 'My Fields',
    seeAll: 'See All',
    expertTools: 'Expert Tools',
    cropSelection: 'Crop Selection',
    diseaseDetection: 'Disease Detection',
    fieldMapping: 'Field Mapping',
    farmingTips: 'Farming Tips',
    weeklyFocus: 'Weekly Focus',
    waterUsage: 'Best Water Usage in Drought',
    readGuide: 'Read Guide',
    soilHealth: 'Soil Health Diagnosis',
    weatherImpact: 'Weather Impact',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    phLevel: 'pH Level',
    ideal: 'Ideal',
    medium: 'Medium',
    high: 'High',
    acidic: 'Acidic',
    scanCrops: 'Scan your crops for problems',
    scanDesc: 'Our AI analyzes leaf patterns to instantly identify diseases and provide expert-approved remedies.',
    uploadCapture: 'Upload or Capture Crop Image',
    uploadDesc: 'Take a clear picture of the affected leaf. Ensure sufficient natural light for best results.',
    openCamera: 'Open Camera',
    selectGallery: 'Select from Gallery',
    expertAdvice: 'Expert Advice',
    waitingImage: 'Waiting for image...',
    identified: 'Identified',
    riceBlast: 'Rice Blast Fungus',
    recommendedActions: 'Recommended Actions',
    irrigationControl: 'Irrigation Control',
    fungicideApp: 'Fungicide Application',
    buyRemedy: 'Buy Remedy',
    fieldMapper: 'Field Mapper',
    myLand: 'My Land',
    manageLand: 'Manage your agricultural land perfectly.',
    activeFields: 'Active Fields',
    avgMoisture: 'Avg. Moisture Level',
    savedPlots: 'Saved Plots',
    area: 'Area',
    soilType: 'Soil Type',
    growth: 'Growth',
    signup: 'Create New Account',
    signupDesc: 'Start your smart farming journey.',
    name: 'Name',
    phone: 'Phone Number',
    district: 'District',
    selectDistrict: 'Select your district',
    agreeTerms: 'I agree to the terms.',
    createAccount: 'Create Account',
    alreadyAccount: 'Already have an account?',
    knowledgeCenter: 'Knowledge Center',
    expertConsultation: 'Expert Advice',
    seasonalInsights: 'Seasonal Insights',
    allMethods: 'All Methods',
    cropTips: 'Crop Tips',
    seasonal: 'Seasonal',
    pestAlert: 'Pest Alert',
    leafhopper: 'Leafhopper Detection',
    tomatoCare: 'Crop Tips: Tomato Care',
    toolCare: 'Best Practice: Tool Care',
    smartIrrigation: 'Smart Irrigation System',
    moreAdvice: 'See More Advice',
    pageOf: 'Page {current} of {total}',
    logout: 'Logout from Account',
    weatherForecast: 'Weather Forecast',
    voiceAssistant: 'Voice Assistant',
    aiRecommendations: 'AI Recommendations',
    scanCropDesc: 'Scan Crop',
    satelliteAnalysis: 'Satellite Analysis',
    bestPracticesDesc: 'Best Practices',
    sevenDayOutlook: '7-Day Farming Outlook',
    banglaEnglishAI: 'Bangla & English AI',
    noFieldsMapped: 'No fields mapped yet',
    addFirstField: 'Add First Field',
    loadingFields: 'Loading fields...',
    statusHealthy: 'Healthy',
    statusAttention: 'Attention',
    statusCritical: 'Critical',
    statusUnknown: 'Unknown',
    gpsMapped: 'GPS Mapped',
    simpleMode: 'Simple',
    accountManagement: 'Account Management',
    totalArea: 'Total Area',
    activeFieldsLabel: 'Active Fields',
    manageLandBoundaries: 'Manage health & boundaries',
    myCrops: 'My Crops',
    yieldTracking: 'Yield tracking & pest control',
    languageSettings: 'Language Settings',
    switchLanguage: 'Switch between English and Bangla',
    appSettings: 'App Settings',
    notificationsPrivacy: 'Notifications & Privacy',
    aiEngine: 'AI Recommendation Engine',
    optimizeHarvest: 'Optimize Your Harvest',
    fieldAwareDesc: 'Field-aware AI crop recommendations powered by weather & soil data.',
    newRecommendation: 'New',
    historyTab: 'History',
    selectField: 'Select Field (optional)',
    noFieldSelected: 'No field selected (use device location)',
    noneDeviceLocation: 'None (use device location)',
    noSavedFields: 'No saved fields. Add fields in the Fields tab.',
    fetchingWeather: 'Fetching weather...',
    weatherUnavailable: 'Weather unavailable',
    soilData: 'Soil Data',
    soilTypeLabel: 'Soil Type',
    fertilityLabel: 'Fertility',
    phLevelLabel: 'pH Level',
    moisturePct: 'Moisture %',
    npkValues: 'NPK Values (mg/kg) *',
    getRecommendations: 'Get AI Recommendations',
    analyzing: 'Analyzing...',
    savingLabel: 'Saving...',
    aiInsight: 'AI Insight',
    topRecommendations: 'Top Recommendations',
    matchLabel: '% Match',
    seasonLabel: 'Season: ',
    resumeDraft: 'Resume',
    discardDraft: 'Discard',
    savedToHistory: '\u2713 Saved to your recommendation history',
    noRecommendations: 'No recommendations yet',
    generateFirst: 'Generate your first crop recommendation.',
    getStartedBtn: 'Get Started',
    // Dashboard
    totalFields: 'Total Fields', activeCrops: 'Active Crops', healthAlerts: 'Alerts',
    dailyAiInsight: 'Daily AI Insight', generatingGuide: 'Generating AI Daily Guide...',
    goodMorning: 'Good Morning', goodAfternoon: 'Good Afternoon', goodEvening: 'Good Evening',
    farmOverview: 'Farm Overview', recentActivity: 'Recent Activity', viewAll: 'View All',
    addField: 'Add Field', noActivity: 'No recent activity',
    // Map controls
    streetView: '🗺 Street', topoView: '⛰ Topo', satelliteView: '🛰 Satellite',
    osmAttribution: '© OpenStreetMap contributors',
    // Field Detail Panel
    activeCropLabel: 'Active Crop', noActiveCrop: 'No active crop set',
    getAiCropRec: 'Get AI Crop Recommendation',
    viewRoadmap: 'View Roadmap', hideRoadmap: 'Hide Roadmap',
    cultivationRoadmap: 'Cultivation Roadmap', viewFullRoadmap: 'View Full Roadmap Screen',
    generatingRoadmap: 'Generating roadmap…', roadmapError: 'Could not generate roadmap. Try again.',
    roadmapProgress: 'Progress', phases: 'phases',
    soilPh: 'Soil pH', gpsPoints: 'GPS Points', soilTypeLabel2: 'Soil Type',
    updateFieldHealth: 'Update Field Health', renameField: 'Rename Field',
    loadAiRoadmap: 'Load AI Cultivation Roadmap',
    deleteField: 'Delete Field', cropRecommendation: 'Crop Recommendation',
    scanDisease: 'Scan for Disease', gpsMapped: 'GPS Mapped', simpleLabel: 'Simple Mode',
    // Add Field flow
    chooseMode: 'Choose mapping mode',
    gpsModeTitle: 'GPS Walk Mode', gpsModeDesc: 'Walk your field boundary and tap to mark points',
    simpleModeTitle: 'Simple Mode', simpleModeDesc: 'One GPS point + enter area manually',
    markPoint: 'Mark Point', doneReview: 'Done — Review Field',
    calcAreaLabel: 'Calculated Area', correctionLabel: 'Area Correction (optional)',
    actualArea: 'Actual measured area', applyFix: 'Apply Fix',
    correctionNote: 'If the calculated area differs from your records, enter the correct value to rescale.',
    cancel: 'Cancel', saveField: 'Save Field', saving: 'Saving…',
    fieldNamePlaceholder: 'Field name (required)', backToMarking: '← Back to marking',
    addNewField: 'Add New Field', noFieldsYet: 'No fields yet', addFirstFieldHint: 'Add your first field above',
    // Knowledge Center
    askAiTab: 'Ask AI', pestCalendarTab: 'Pest Calendar', quickGuidesTab: 'Quick Guides',
    infoHub: 'Information Hub', expertKnowledge: 'Expert Knowledge',
    expertKnowledgeDesc: 'Ask AI questions, track seasonal pests, and access farming best practices.',
    getCropRecBtn: 'Get Crop Recommendations', tryNow: 'Try Now',
    askAiTitle: 'Ask the AI Agronomist', askAiDesc: 'Get expert answers in Bengali or English',
    typeQuestion: 'Type your farming question…',
    pestCalendarTitle: 'Seasonal Pest Calendar',
    pestCalendarDesc: 'Bangladesh crop calendar — tap a month to expand threats',
    watchPests: '⚠️ Watch for Pests', activecropsLabel: '🌾 Active Crops', current: 'Current',
    quickGuidesTitle: 'Farming Quick Guides', quickGuidesDesc: 'Best practices every Bangladeshi farmer should know',
    fullLibrary: 'Full Farming Guides Library', readTime: '5–15 min reads',
    aiPowered: 'AI Powered',
    // Guide Detail
    todaysGoal: "Today's Essential Goal", detailedSteps: 'Detailed Steps for Success',
    proTipTitle: "Agronomist's Pro Tip", seasonLabel2: 'Season', focusLabel: 'Focus',
    minRead: '5 min read', saveGuide: 'Save Guide', share: 'Share',
    savedConfirm: 'Saved!', copiedConfirm: 'Copied!',
    askAgronomist: 'Ask the AI Agronomist', aiAnswerLabel: 'AI Agronomist Answer',
    returnDashboard: 'Return to Dashboard', noGuideSelected: 'No guide selected.',
    generateFresh: 'Generate fresh version', backToDashboard: 'Dashboard',
    knowledgeCenterBtn: 'Knowledge Center', relatedQuestions: 'Related Questions',
    // Disease Detection
    uploadOrCapture: 'Upload or Capture', analyzingImage: 'Analyzing image…',
    diagnosisResult: 'Diagnosis Result', treatmentPlan: 'Treatment Plan',
    severityLabel: 'Severity', preventionTips: 'Prevention Tips',
    saveHealthReport: 'Save Health Report to Field', selectFieldLabel: 'Select Field',
    saveReport: 'Save Report', scanAnother: 'Scan Another',
    // Crop Roadmap
    activateRoadmap: 'Activate Roadmap', syncedToField: 'Synced to Field',
    syncingRoadmap: 'Syncing…', roadmapFor: 'Cultivation Roadmap for',
    generatingRoadmapFull: 'Generating your roadmap…',
    // Health statuses
    healthHealthy: 'Healthy', healthAttention: 'Attention Needed',
    healthCritical: 'Critical', healthUnknown: 'Unknown',
  },
  bn: {
    appName: 'ডিজিটাল কৃষিবিদ',
    welcome: 'স্বাগতম,',
    manageCrops: 'সঠিকভাবে আপনার ফসল পরিচালনা করুন।',
    login: 'অ্যাকাউন্টে লগইন করুন',
    loginDesc: 'আপনার খামারে প্রবেশ করতে তথ্য প্রদান করুন।',
    phoneOrEmail: 'ফোন বা ইমেইল',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'ভুলে গেছেন?',
    loginBtn: 'ড্যাশবোর্ডে লগইন করুন',
    orContinue: 'অথবা চালিয়ে যান',
    google: 'গুগল',
    otp: 'ওটিপি',
    noAccount: 'অ্যাকাউন্ট নেই?',
    signupFree: 'বিনামূল্যে সাইন আপ করুন',
    getStarted: 'শুরু করুন',
    smartFarmer: 'স্মার্ট কৃষক',
    aiDriven: 'এআই এর সাথে বুদ্ধিমান চাষ',
    accuracy: 'নির্ভুলতা',
    advisor: 'পরামর্শদাতা',
    home: 'হোম',
    fields: 'জমি',
    aiTools: 'এআই টুলস',
    profile: 'প্রোফাইল',
    myFields: 'আমার জমিসমূহ',
    seeAll: 'সব দেখুন',
    expertTools: 'বিশেষজ্ঞ সরঞ্জাম',
    cropSelection: 'ফসল নির্বাচন',
    diseaseDetection: 'রোগ শনাক্তকরণ',
    fieldMapping: 'মাঠ মানচিত্র',
    farmingTips: 'চাষাবাদ টিপস',
    weeklyFocus: 'সাপ্তাহিক গুরুত্ব',
    waterUsage: 'খরার সময় পানির সর্বোত্তম ব্যবহার',
    readGuide: 'গাইডটি পড়ুন',
    soilHealth: 'মাটির স্বাস্থ্যের রোগনির্ণয়',
    weatherImpact: 'আবহাওয়ার প্রভাব',
    nitrogen: 'নাইট্রোজেন (N)',
    phosphorus: 'ফসফরাস (P)',
    potassium: 'পটাশিয়াম (K)',
    phLevel: 'pH মাত্রা',
    ideal: 'আদর্শ',
    medium: 'মাঝারি',
    high: 'উচ্চ',
    acidic: 'অম্লীয়',
    scanCrops: 'সমস্যার জন্য আপনার ফসল স্ক্যান করুন',
    scanDesc: 'আমাদের AI পাতার প্যাটার্ন বিশ্লেষণ করে তাৎক্ষণিকভাবে রোগ শনাক্ত করে এবং বিশেষজ্ঞ-অনুমোদিত প্রতিকার প্রদান করে।',
    uploadCapture: 'ফসলের ছবি আপলোড বা ক্যাপচার করুন',
    uploadDesc: 'আক্রান্ত পাতার একটি পরিষ্কার ছবি নিন। ভালো ফলাফলের জন্য পর্যাপ্ত প্রাকৃতিক আলো নিশ্চিত করুন।',
    openCamera: 'ক্যামেরা খুলুন',
    selectGallery: 'গ্যালারি থেকে নির্বাচন করুন',
    expertAdvice: 'বিশেষজ্ঞ পরামর্শ',
    waitingImage: 'ছবির জন্য অপেক্ষা করছে...',
    identified: 'শনাক্তকৃত',
    riceBlast: 'ধানের ব্লাস্ট ছত্রাক',
    recommendedActions: 'প্রস্তাবিত পদক্ষেপসমূহ',
    irrigationControl: 'সেচ নিয়ন্ত্রণ',
    fungicideApp: 'ছত্রাকনাশক প্রয়োগ',
    buyRemedy: 'প্রতিকার কিনুন',
    fieldMapper: 'ফিল্ড ম্যাপার',
    myLand: 'আমার জমি',
    manageLand: 'আপনার কৃষি জমি নিখুঁতভাবে পরিচালনা করুন।',
    activeFields: 'সক্রিয় জমি',
    avgMoisture: 'গড় আর্দ্রতা লেভেল',
    savedPlots: 'সংরক্ষিত জমি',
    area: 'জমির আকার',
    soilType: 'মাটির ধরন',
    growth: 'বৃদ্ধি',
    signup: 'নতুন অ্যাকাউন্ট তৈরি করুন',
    signupDesc: 'স্মার্ট চাষের যাত্রা শুরু করুন।',
    name: 'নাম',
    phone: 'ফোন নম্বর',
    district: 'জেলা',
    selectDistrict: 'আপনার জেলা নির্বাচন করুন',
    agreeTerms: 'আমি শর্তাবলীর সাথে একমত।',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    alreadyAccount: 'আগে থেকেই অ্যাকাউন্ট আছে?',
    knowledgeCenter: 'তথ্য কেন্দ্র',
    expertConsultation: 'বিশেষজ্ঞ পরামর্শ',
    seasonalInsights: 'মৌসুমি ধারণা।',
    allMethods: 'সব পদ্ধতি',
    cropTips: 'ফসল টিপস',
    seasonal: 'মৌসুমি',
    pestAlert: 'পোকামাকড় সতর্কবার্তা',
    leafhopper: 'লিফহপার শনাক্তকরণ',
    tomatoCare: 'ফসল টিপস: টমেটোর যত্ন',
    toolCare: 'সেরা পদ্ধতি: সরঞ্জামের যত্ন',
    smartIrrigation: 'স্মার্ট সেচ ব্যবস্থা',
    moreAdvice: 'আরও পরামর্শ দেখুন',
    pageOf: 'পৃষ্ঠা {current} এর {total}',
    logout: 'অ্যাকাউন্ট থেকে লগ আউট করুন',
    weatherForecast: 'আবহাওয়া পূর্বাভাস',
    voiceAssistant: 'ভয়েস সহকারী',
    aiRecommendations: 'এআই পরামর্শ',
    scanCropDesc: 'ফসল স্ক্যান',
    satelliteAnalysis: 'স্যাটেলাইট বিশ্লেষণ',
    bestPracticesDesc: 'সেরা পদ্ধতি',
    sevenDayOutlook: '৭ দিনের কৃষি পূর্বাভাস',
    banglaEnglishAI: 'বাংলা ও ইংরেজি এআই',
    noFieldsMapped: 'এখনও কোনো জমি ম্যাপ করা হয়নি',
    addFirstField: 'প্রথম জমি যোগ করুন',
    loadingFields: 'জমি লোড হচ্ছে…',
    statusHealthy: 'সুস্থ',
    statusAttention: 'মনোযোগ প্রয়োজন',
    statusCritical: 'জরুরি',
    statusUnknown: 'অজানা',
    gpsMapped: 'জিপিএস ম্যাপড',
    simpleMode: 'সাধারণ',
    accountManagement: 'অ্যাকাউন্ট ব্যবস্থাপনা',
    totalArea: 'মোট জমির পরিমাণ',
    activeFieldsLabel: 'সক্রিয় জমি',
    manageLandBoundaries: 'স্বাস্থ্য ও সীমানা পরিচালনা',
    myCrops: 'আমার ফসল',
    yieldTracking: 'ফলন ট্র্যাকিং ও কীটপতঙ্গ নিয়ন্ত্রণ',
    languageSettings: 'ভাষা সেটিংস',
    switchLanguage: 'ইংরেজি ও বাংলার মধ্যে পরিবর্তন করুন',
    appSettings: 'অ্যাপ সেটিংস',
    notificationsPrivacy: 'বিজ্ঞপ্তি ও গোপনীয়তা',
    aiEngine: 'এআই সুপারিশ ইঞ্জিন',
    optimizeHarvest: 'আপনার ফলন অপ্টিমাইজ করুন',
    fieldAwareDesc: 'আবহাওয়া ও মাটির তথ্য দিয়ে মাঠ-সচেতন এআই ফসল সুপারিশ।',
    newRecommendation: 'নতুন',
    historyTab: 'ইতিহাস',
    selectField: 'জমি নির্বাচন করুন (ঐচ্ছিক)',
    noFieldSelected: 'কোনো জমি নির্বাচিত নয় (ডিভাইসের অবস্থান ব্যবহার)',
    noneDeviceLocation: 'কোনোটি নয় (ডিভাইসের অবস্থান)',
    noSavedFields: 'কোনো সংরক্ষিত জমি নেই। জমি ট্যাবে জমি যোগ করুন।',
    fetchingWeather: 'আবহাওয়া আনা হচ্ছে…',
    weatherUnavailable: 'আবহাওয়া পাওয়া যায়নি',
    soilData: 'মাটির তথ্য',
    soilTypeLabel: 'মাটির ধরন',
    fertilityLabel: 'উর্বরতা',
    phLevelLabel: 'pH মাত্রা',
    moisturePct: 'আর্দ্রতা %',
    npkValues: 'NPK মান (mg/kg) *',
    getRecommendations: 'এআই সুপারিশ নিন',
    analyzing: 'বিশ্লেষণ করা হচ্ছে…',
    savingLabel: 'সংরক্ষণ করা হচ্ছে…',
    aiInsight: 'এআই অন্তর্দৃষ্টি',
    topRecommendations: 'শীর্ষ সুপারিশ',
    matchLabel: '% উপযুক্ত',
    seasonLabel: 'মৌসুম: ',
    resumeDraft: 'পুনরায় শুরু করুন',
    discardDraft: 'বাতিল করুন',
    savedToHistory: '\u2713 সুপারিশ ইতিহাসে সংরক্ষিত হয়েছে',
    noRecommendations: 'এখনও কোনো সুপারিশ নেই',
    generateFirst: 'আপনার প্রথম ফসল সুপারিশ তৈরি করুন।',
    getStartedBtn: 'শুরু করুন',
    // Dashboard
    totalFields: 'মোট জমি', activeCrops: 'সক্রিয় ফসল', healthAlerts: 'সতর্কতা',
    dailyAiInsight: 'দৈনিক এআই গাইড', generatingGuide: 'এআই গাইড তৈরি হচ্ছে...',
    goodMorning: 'শুভ সকাল', goodAfternoon: 'শুভ দুপুর', goodEvening: 'শুভ সন্ধ্যা',
    farmOverview: 'খামারের সারসংক্ষেপ', recentActivity: 'সাম্প্রতিক কার্যক্রম', viewAll: 'সব দেখুন',
    addField: 'জমি যোগ করুন', noActivity: 'কোনো সাম্প্রতিক কার্যক্রম নেই',
    // Map controls
    streetView: '🗺 মানচিত্র', topoView: '⛰ ভূখণ্ড', satelliteView: '🛰 স্যাটেলাইট',
    osmAttribution: '© OpenStreetMap অবদানকারী',
    // Field Detail Panel
    activeCropLabel: 'সক্রিয় ফসল', noActiveCrop: 'কোনো সক্রিয় ফসল নেই',
    getAiCropRec: 'এআই ফসল সুপারিশ নিন',
    viewRoadmap: 'রোডম্যাপ দেখুন', hideRoadmap: 'রোডম্যাপ লুকান',
    cultivationRoadmap: 'চাষ পরিকল্পনা', viewFullRoadmap: 'পূর্ণ রোডম্যাপ দেখুন',
    generatingRoadmap: 'রোডম্যাপ তৈরি হচ্ছে…', roadmapError: 'রোডম্যাপ তৈরি করা যায়নি। আবার চেষ্টা করুন।',
    roadmapProgress: 'অগ্রগতি', phases: 'ধাপ',
    soilPh: 'মাটির pH', gpsPoints: 'জিপিএস পয়েন্ট', soilTypeLabel2: 'মাটির ধরন',
    updateFieldHealth: 'জমির স্বাস্থ্য আপডেট করুন', renameField: 'জমির নাম পরিবর্তন',
    loadAiRoadmap: 'এআই চাষ পরিকল্পনা লোড করুন',
    deleteField: 'জমি মুছুন', cropRecommendation: 'ফসল সুপারিশ',
    scanDisease: 'রোগ স্ক্যান করুন', gpsMapped: 'জিপিএস ম্যাপড', simpleLabel: 'সাধারণ মোড',
    // Add Field flow
    chooseMode: 'ম্যাপিং পদ্ধতি বেছে নিন',
    gpsModeTitle: 'জিপিএস ওয়াক মোড', gpsModeDesc: 'জমির সীমানা বরাবর হেঁটে পয়েন্ট চিহ্নিত করুন',
    simpleModeTitle: 'সাধারণ মোড', simpleModeDesc: 'একটি জিপিএস পয়েন্ট + ম্যানুয়ালি জমির পরিমাণ লিখুন',
    markPoint: 'পয়েন্ট চিহ্নিত করুন', doneReview: 'সম্পন্ন — জমি পর্যালোচনা',
    calcAreaLabel: 'হিসাবকৃত জমির পরিমাণ', correctionLabel: 'জমির সংশোধন (ঐচ্ছিক)',
    actualArea: 'প্রকৃত পরিমাণ', applyFix: 'সংশোধন করুন',
    correctionNote: 'যদি হিসাবকৃত পরিমাণ ভুল হয়, সঠিক মান লিখুন।',
    cancel: 'বাতিল', saveField: 'জমি সংরক্ষণ করুন', saving: 'সংরক্ষণ হচ্ছে…',
    fieldNamePlaceholder: 'জমির নাম (আবশ্যক)', backToMarking: '← পয়েন্ট চিহ্নিতকরণে ফিরুন',
    addNewField: 'নতুন জমি যোগ করুন', noFieldsYet: 'এখনো কোনো জমি নেই', addFirstFieldHint: 'উপরে প্রথম জমি যোগ করুন',
    // Knowledge Center
    askAiTab: 'এআই জিজ্ঞাসা', pestCalendarTab: 'পোকার ক্যালেন্ডার', quickGuidesTab: 'দ্রুত গাইড',
    infoHub: 'তথ্য কেন্দ্র', expertKnowledge: 'বিশেষজ্ঞ জ্ঞান',
    expertKnowledgeDesc: 'এআইকে প্রশ্ন করুন, মৌসুমি পোকা ট্র্যাক করুন এবং কৃষি পদ্ধতি জানুন।',
    getCropRecBtn: 'ফসল সুপারিশ নিন', tryNow: 'এখনই চেষ্টা করুন',
    askAiTitle: 'এআই কৃষিবিদকে জিজ্ঞাসা করুন', askAiDesc: 'বাংলা বা ইংরেজিতে বিশেষজ্ঞ উত্তর পান',
    typeQuestion: 'আপনার কৃষি প্রশ্ন লিখুন…',
    pestCalendarTitle: 'মৌসুমি পোকার ক্যালেন্ডার',
    pestCalendarDesc: 'বাংলাদেশ ফসল ক্যালেন্ডার — মাস ট্যাপ করুন',
    watchPests: '⚠️ পোকার সতর্কতা', activecropsLabel: '🌾 সক্রিয় ফসল', current: 'চলতি',
    quickGuidesTitle: 'কৃষি দ্রুত গাইড', quickGuidesDesc: 'প্রতিটি বাংলাদেশী কৃষকের জানা উচিত',
    fullLibrary: 'সম্পূর্ণ কৃষি গাইড লাইব্রেরি', readTime: '৫-১৫ মিনিটের পড়া',
    aiPowered: 'এআই চালিত',
    // Guide Detail
    todaysGoal: 'আজকের প্রধান লক্ষ্য', detailedSteps: 'সাফল্যের বিস্তারিত ধাপ',
    proTipTitle: 'কৃষিবিদের বিশেষ পরামর্শ', seasonLabel2: 'মৌসুম', focusLabel: 'মনোযোগ',
    minRead: '৫ মিনিটের পড়া', saveGuide: 'গাইড সংরক্ষণ', share: 'শেয়ার করুন',
    savedConfirm: 'সংরক্ষিত!', copiedConfirm: 'কপি হয়েছে!',
    askAgronomist: 'এআই কৃষিবিদকে জিজ্ঞাসা করুন', aiAnswerLabel: 'এআই কৃষিবিদের উত্তর',
    returnDashboard: 'ড্যাশবোর্ডে ফিরুন', noGuideSelected: 'কোনো গাইড নির্বাচিত হয়নি।',
    generateFresh: 'নতুন সংস্করণ তৈরি করুন', backToDashboard: 'ড্যাশবোর্ড',
    knowledgeCenterBtn: 'তথ্য কেন্দ্র', relatedQuestions: 'সম্পর্কিত প্রশ্ন',
    // Disease Detection
    uploadOrCapture: 'ছবি আপলোড বা তোলা', analyzingImage: 'ছবি বিশ্লেষণ হচ্ছে…',
    diagnosisResult: 'রোগ নির্ণয়ের ফলাফল', treatmentPlan: 'চিকিৎসা পরিকল্পনা',
    severityLabel: 'তীব্রতা', preventionTips: 'প্রতিরোধের পরামর্শ',
    saveHealthReport: 'জমিতে স্বাস্থ্য রিপোর্ট সংরক্ষণ', selectFieldLabel: 'জমি নির্বাচন করুন',
    saveReport: 'রিপোর্ট সংরক্ষণ', scanAnother: 'আরেকটি স্ক্যান করুন',
    // Crop Roadmap
    activateRoadmap: 'রোডম্যাপ সক্রিয় করুন', syncedToField: 'জমিতে সিঙ্ক হয়েছে',
    syncingRoadmap: 'সিঙ্ক হচ্ছে…', roadmapFor: 'চাষ পরিকল্পনা:',
    generatingRoadmapFull: 'আপনার রোডম্যাপ তৈরি হচ্ছে…',
    // Health statuses
    healthHealthy: 'সুস্থ', healthAttention: 'মনোযোগ প্রয়োজন',
    healthCritical: 'জরুরি অবস্থা', healthUnknown: 'অজানা',
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: ReactNode }) {
  const { currentUser, updateUserSettings } = useAuth();
  const [language, setLanguageState] = useState<Language>('bn');

  // Load language from Firestore when user is logged in
  useEffect(() => {
    if (!currentUser) return;
    
    const settingsDocRef = doc(db, `users/${currentUser.uid}/settings/profile`);
    const unsubscribe = onSnapshot(settingsDocRef, (snap) => {
      if (snap.exists()) {
        const data = snap.data();
        if (data.language) {
          setLanguageState(data.language as Language);
        }
      }
    });

    return () => unsubscribe();
  }, [currentUser]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (currentUser) {
      updateUserSettings({ language: lang });
    }
  };

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <AppContext.Provider value={{ language, setLanguage, t }}>
      <div lang={language}>
        {children}
      </div>
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) throw new Error('useApp must be used within AppProvider');
  return context;
}
